### ISSUE TITLE
I loaded python/2.7 but got this error

### ISSUE THREAD

**Issue by liuyin111** [hart-lab/drugz#10]
INFO:__main__:Initiating analysis
INFO:__main__:Loading the read count matrix
INFO:__main__:Normalizing read counts
INFO:__main__:Calculating raw fold change for replicate 1
INFO:__main__:Caculating smoothed Epirical Bayes estimates of stdev for replicate 1
INFO:__main__:Caculating guide-level Zscores for replicate 1
Traceback (most recent call last):
  File "drugz.py", line 478, in <module>
    main()
  File "drugz.py", line 475, in main
    drugZ_analysis(args)
  File "drugz.py", line 458, in drugZ_analysis
    fold_change =pd.concat(fold_changes, axis=1, sort=False)
TypeError: concat() got an unexpected keyword argument 'sort'

**Comment by mcolic** [comment]
Hi,
drugZ is python3 based. Therefore, using python3 and pandas > 1.0.x, should resolve your error.
Best,
Medina

**Comment by liuyin111** [comment]
Yes, it works now. Thanks for the explanation.
