### ISSUE TITLE
foldchange report with no lines

### ISSUE THREAD

**Issue by jflucier** [hart-lab/drugz#11]
Hi,

I run the drugz soft on readcount files downloaded from a published study. The soft runs fine with no error and drugz report is complete. However, foldchange file does not output any line.

File IR.drugz-output.tsv contains 17943 lines. Here are the head output of file:
> head IR.drugz-output.tsv
GENE	sumZ	numObs	normZ	pval_synth	rank_synth	fdr_synth	pval_supp	rank_supp	fdr_supp
LIG4	-26.06	8	-8.96	1.6e-19	1	2.88e-15	1	17942	1
NHEJ1	-25.13	8	-8.64	2.86e-18	2	2.57e-14	1	17941	1
ATM	-19.75	6	-7.83	2.45e-15	3	1.47e-11	1	17940	1
FAM35A	-19.65	8	-6.73	8.74e-12	4	3.92e-08	1	17939	1
PNKP	-16.08	8	-5.48	2.09e-08	5	7.48e-05	1	17938	1
AMBRA1	-15.48	8	-5.27	6.72e-08	6	0.000201	1	17937	1
C7orf49	-14.39	8	-4.89	4.93e-07	7	0.00126	1	17936	1
C20orf196	-14.25	8	-4.84	6.36e-07	8	0.00131	1	17935	1
RNF168	-14.23	8	-4.84	6.56e-07	9	0.00131	1	17934	1

Files IR.drugz-foldchange.tsv contains 0 lines

I called drugz the following way:
python /ip29/marechal_group/programs/drugz/drugz.py -i Dataset_S1_readcounts.txt -o IR.drugz-output.tsv -f IR.drugz-foldchange.tsv -c S08_NT_T18_A,S08_NT_T18_B -x S08_IR_T18_A,S08_IR_T18_B

Thanks alot for your help,
JF

**Comment by mcolic** [comment]
Hi JF,

Please try again, it should work now.. The lines for storing the fc output to a file have been commented out.

Best,
-M

**Comment by jflucier** [comment]
Now it works.

thank you
JF
